export default function Home() {
  return (
    <>
      <div class="max-w-[1000px] min-h-screen mx-auto py-20 px-4">
      <h2 class="text-xl font-semibold mb-4 text-red-500">Last updated: May 14, 2024</h2>

      <h1 class="text-5xl font-bold mb-10">Privacy Policy</h1>
      <div class="flex flex-col gap-10">
        <p class="text-lg sm:pl-10">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.

          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.  
        </p>
        <h2 class="text-3xl font-bold mb-2">1. Interpretation and Definitions</h2>
        <h3 className="text-lg font-bold mt-2">Interpretation</h3>
        <p class="text-lg sm:pl-10">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
        <h3 className="text-lg font-bold mt-2">Definitions</h3>
        <p class="text-lg sm:pl-10">For the purposes of this Privacy Policy:</p>
        <ul>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- Account</strong> means a unique account created for You to
              access our Service or parts of our Service.
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- Extension</strong> refers to Jable-Helper, the software
              program provided by the SubtitleX.
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- Developer</strong> (referred to as either &quot;the
              Developer&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot;
              in this Agreement) refers to subtitlex.xyz.
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- Country</strong> refers to: Ontario, Canada
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- Device</strong> means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- Personal Data</strong> is any information that relates to
              an identified or identifiable individual.
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- Service</strong> refers to the Extension.
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- Application</strong> refers to the Extension.
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- Usage Data</strong> refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself (for example, the duration of a
              page visit).
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- You</strong> means the individual accessing or using the
              Service, or the Developer, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </p>
          </li>
        </ul>
        <h2 class="text-3xl font-bold mb-2">2. Collecting and Using Your Personal Data</h2>
        <h3 className="text-lg font-bold mt-2">Types of Data Collected</h3>
        <h4 className="font-bold mt-1">a. Personal Data</h4>
        <p class="text-lg sm:pl-10">
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ul className="px-4">
          <li>
            <p class="text-lg sm:pl-10">- Email address</p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">- Usage Data</p>
          </li>
        </ul>
        <h4 className="font-bold mt-1">b. Usage Data</h4>
        <p class="text-lg sm:pl-10">Usage Data is collected automatically when using the Service.</p>
        <p class="text-lg sm:pl-10">
          Usage Data may include information such as Your Device&#39;s Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
        </p> 
        <h3 className="text-lg font-bold mt-2">Use of Your Personal Data</h3>
        <p class="text-lg sm:pl-10">The Service may use Personal Data for the following purposes:</p>
        <ul>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- To provide and maintain our Service</strong>, including to
              monitor the usage of our Service.
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- To manage Your Account:</strong> to manage Your
              subscription as a user of the Service. The Personal Data You
              provide can give You access to different functionalities of the
              Service that are available to You as a subscribed user.
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- For the performance of a contract:</strong> the
              development, compliance and undertaking of the purchase contract
              for the products, items or services You have purchased or of any
              other contract with Us through the Service.
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- To manage Your requests:</strong> To attend and manage
              Your requests to Us.
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- For business transfers:</strong> We may use Your
              information to evaluate or conduct a merger, divestiture,
              restructuring, reorganization, dissolution, or other sale or
              transfer of some or all of Our assets, whether as a going concern
              or as part of bankruptcy, liquidation, or similar proceeding, in
              which Personal Data held by Us about our Service users is among
              the assets transferred.
            </p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              <strong>- For other purposes</strong>: We may use Your information
              for other purposes, such as data analysis, identifying usage
              trends, determining the effectiveness of our promotional campaigns
              and to evaluate and improve our Service, products, services,
              marketing and your experience.
            </p>
          </li>
        </ul>
       
        <h3 className="text-lg font-bold mt-2">Retention of Your Personal Data</h3>
        <p class="text-lg sm:pl-10">
          The Developer will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.
        </p>
        <p class="text-lg sm:pl-10">
          The Developer will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period of
          time, except when this data is used to strengthen the security or to
          improve the functionality of Our Service, or We are legally obligated
          to retain this data for longer time periods.
        </p>
        <h3 className="text-lg font-bold mt-2">Transfer of Your Personal Data</h3>
        <p class="text-lg sm:pl-10">
          Your information, including Personal Data, is processed at the
          Developer&#39;s operating offices and in any other places where the parties
          involved in the processing are located. It means that this information
          may be transferred to — and maintained on — computers located outside
          of Your state, province, country or other governmental jurisdiction
          where the data protection laws may differ than those from Your
          jurisdiction.
        </p>
        <p class="text-lg sm:pl-10">
          Your consent to this Privacy Policy followed by Your submission of
          such information represents Your agreement to that transfer.
        </p>
        <p class="text-lg sm:pl-10">
          The Developer will take all steps reasonably necessary to ensure that
          Your data is treated securely and in accordance with this Privacy
          Policy and no transfer of Your Personal Data will take place to an
          organization or a country unless there are adequate controls in place
          including the security of Your data and other personal information.
        </p>
        <h3 className="text-lg font-bold mt-2">Delete Your Personal Data</h3>
        <p class="text-lg sm:pl-10">
          You have the right to delete or request that We assist in deleting the
          Personal Data that We have collected about You.
        </p>
        <p class="text-lg sm:pl-10">
          You may update, amend, or delete Your information at any time by
          signing in to Your Account, if you have one, and visiting the account
          settings section that allows you to manage Your personal information.
          You may also contact Us to request access to, correct, or delete any
          personal information that You have provided to Us.
        </p>
        <p class="text-lg sm:pl-10">
          Please note, however, that We may need to retain certain information
          when we have a legal obligation or lawful basis to do so.
        </p>
        <h3 className="text-lg font-bold mt-2">Disclosure of Your Personal Data</h3>
        <h4 className="font-bold mt-1">Business Transactions</h4>
        <p class="text-lg sm:pl-10">
          If the Developer is involved in a merger, acquisition or asset sale,
          Your Personal Data may be transferred. We will provide notice before
          Your Personal Data is transferred and becomes subject to a different
          Privacy Policy.
        </p>
        <h4 className="font-bold mt-1">Law enforcement</h4>
        <p class="text-lg sm:pl-10">
          Under certain circumstances, the Developer may be required to disclose
          Your Personal Data if required to do so by law or in response to valid
          requests by public authorities (e.g. a court or a government agency).
        </p>
        <h4 className="font-bold mt-1">Other legal requirements</h4>
        <p class="text-lg sm:pl-10">
          The Developer may disclose Your Personal Data in the good faith belief
          that such action is necessary to:
        </p>
        <ul className="px-12">
          <li>- Comply with a legal obligation</li>
          <li>- Protect and defend the rights or property of the Developer</li>
          <li>
            - Prevent or investigate possible wrongdoing in connection with the
            Service
          </li>
          <li>
            - Protect the personal safety of Users of the Service or the public
          </li>
          <li>- Protect against legal liability</li>
        </ul>
        <h3 className="text-lg font-bold mt-2">Security of Your Personal Data</h3>
        <p class="text-lg sm:pl-10">
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use every
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.
        </p>
        <h2 class="text-3xl font-bold mb-2">3. Children&#39;s Privacy</h2>
        <p class="text-lg sm:pl-10">
         This service is not intending to serve children.
          If We become aware that We have collected Personal Data from anyone
          under the age of 18 without verification of parental consent, We take
          steps to remove that information from Our servers.
        </p>

        <h2 class="text-3xl font-bold mb-2">4. Changes to this Privacy Policy</h2>
        <p class="text-lg sm:pl-10">
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p class="text-lg sm:pl-10">
          We will let You know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective and update the
          &quot;Last updated&quot; date at the top of this Privacy Policy.
        </p>
        <p class="text-lg sm:pl-10">
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
        <h2 class="text-3xl font-bold mb-2">5. Contact Us</h2>
        <p class="text-lg sm:pl-10">
          If you have any questions about this Privacy Policy, You can contact
          us:
        </p>
        <ul>
          <li>
            <p class="text-lg sm:pl-10">By email: subtitlex.xyz@gmail.com</p>
          </li>
          <li>
            <p class="text-lg sm:pl-10">
              By visiting this page on our website:  
              <a
                href="https://www.subtitlex.xyz/Memeber"
                rel="external nofollow noopener"
                target="_blank"
              >
                https://www.subtitlex.xyz/Memeber
              </a>
            </p>
          </li>
        </ul></div>
      </div>
    </>
  );
}
